# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5fcbd2bf7d8c4d2d5278bc2248f3a5d3f200e76b18149ece0cf6f8ba2f3201ff67d4cd7e6343013333524de0be4d297aa7139e5330984e50fbecc71f0052109

test:
  secret_key_base: 2395b50ce51ddb851422c41651c80d4cd9845764e7b2acb97174baf4995e2e275524f65cdb51dc729a60ae5b61d8043b776d2ede07916fd676bcd9e783e0036b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
